### ISSUE TITLE
supporting mutiple alerts

### ISSUE THREAD

**Issue by ronalds1** [TeamnetGroup/cap-net#55]
from what I'm understanding, multiple alerts will be wrapped in the edxlde element but there is nothing in your code doing this..  Is it being considered in the next release ?

![image](https://cloud.githubusercontent.com/assets/9359298/6796406/ada165ce-d246-11e4-8e51-081ba4ee6a15.png)

**Comment by vgrigoriu** [comment]
Multiple alerts _can_ be wrapped in EDXL-DE (but they can also be wrapped in Atom or anything else). The focus of this project, for now, is just the CAP protocol. If you only want to produce (not consume) multiple alerts wrapped in EDXL-DE, you can use something like this:
```csharp
    IEnumerable<Alert> alerts = GetAlerts();

    XNamespace edxldens = "urn:oasis:names:tc:emergency:EDXL:DE:2.0";
    var root = new XElement(edxldens + "EDXLDistribution",
        new XElement(edxldens + "distributionID", "test message"),
        new XElement(edxldens + "senderID", "some sender"),
        alerts.Select(alert =>
            new XElement(edxldens + "contentObject",
                new XElement(edxldens + "contentDescription", "This is a list of alerts"),
                new XElement(edxldens + "xmlContent", new XElement(edxldens + "embeddedXMLContent", XmlCreator.Create(alert))))));
```

Do you feel it would be useful to have this code wrapped in some utility class/method in CAP.NET?

**Comment by ronalds1** [comment]
thanks..   yes it would be very useful..   this is what we use in Australia.  Also within the "Info" section, i cannot see a way to add "language" element..

**Comment by vgrigoriu** [comment]
The `Info` class has a `Language` property. No promises for the EDXL code, it's a busy period but maybe I'll whip something up in the weekend.

**Comment by ronalds1** [comment]
sounds good to me mate..    we'll get in touch again next week

**Comment by vgrigoriu** [comment]
I implemented the bare minimum of EDXL-DE. It's published as a pre-release [NuGet package](https://www.nuget.org/packages/edxl-net). For an example of how to use it, take a look at [this test](https://github.com/TeamnetGroup/cap-net/blob/503a0da281ce9a07be0f6a3809717028b101ba39/src/EDXLNet.Tests/EdxlDeXmlCreatorTests.cs).

Your example uses EDXL-DE 1.0, but I decided to go with 2.0.

Let me know if this works for you.

**Comment by ronalds1** [comment]
@vgrigoriu ...   do you support "thin" feeds ?

**Comment by vgrigoriu** [comment]
By thin clients do you mean Atom or RSS?

What do you mean you "cannot see" the nuget? Is the link above not working for you? Or is it that you can't see the package in Visual Studio?

**Comment by ronalds1** [comment]
@vgrigoriu 

#1 nuget.  Yes i cannot see the new prerelease in nuget explorer in Visual Studio.

#2 thin feed.  for example, please refer to http://publicalert.pagasa.dost.gov.ph/feeds/  and http://publicalert.pagasa.dost.gov.ph/output/acp/e38557be-567a-4a1d-b4c7-7f821ebc666b.cap

As you can see each alerts are generated in its own file with having one link file pointing to each alert CAP file.

**Comment by vgrigoriu** [comment]
There's a drop down at the top of the nuget window where you can select "Stable Only" or "Include Prerelease". When I search for edxl, I can see this package only when "Include Prerelease" is selected.

Those feeds are Atom, a separate standard. To generate those you can use, for example, the SyndicationFeed class from the .NET Framework: https://msdn.microsoft.com/en-us/library/system.servicemodel.syndication.syndicationfeed%28v=vs.110%29.aspx
